In [ ]:
#Introducción
Platzi -Escuela de Ciencia de Datos 

*Transformación de datos*

# Llamar los datos

In [1]:
#Llamamos el set de datos público 
Chicago_data = 'https://raw.githubusercontent.com/terranigmark/curso-analisis-exploratorio-datos-platzi/main/Traffic_Crashes1.csv'

token_map_plot='pk.eyJ1IjoiY2hlbWlza3kiLCJhIjoiY2tnOGNhcXk3MGZ3eDJ5b2FxZ3ViajN1MyJ9.t3R24lWTwzTQwyJw4vuWFw'

In [2]:
import pandas as pd

In [3]:
Chicago_df=pd.read_csv(Chicago_data,error_bad_lines=False)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
Chicago_df.head()

,Unnamed: 0,CRASH_RECORD_ID,RD_NO,CRASH_DATE_EST_I,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,...,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION,date_real
0,290702,9e97e92753166de921a0e87199513aa841142c6fbb3a1e...,JA154528,NaN,2017-02-14 10:00:00,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,...,0.0,1.0,0.0,10,3,2,42.001676,-87.666364,POINT (-87.666364005301 42.001675862416),2017-02-14
1,405524,e5fe82ab7757d630a7f79927113bc63b5bede0cda74665...,JC391213,NaN,2019-08-13 19:12:00,35,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,...,0.0,8.0,0.0,19,3,8,41.940041,-87.650923,POINT (-87.650923222567 41.940040917032),2019-08-13
2,261834,8c8ea6db9e1950765419429e2732ba5598fc6f87ac9e0c...,JC273287,NaN,2019-05-22 08:30:00,25,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,RAIN,DAYLIGHT,...,0.0,2.0,0.0,8,4,5,41.955854,-87.710645,POINT (-87.710644534923 41.955853610383),2019-05-22
3,38519,02671b7d36a9d189d607778816fec23bbb2e5ac3cd3039...,JA307115,NaN,2017-06-14 16:50:00,0,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,...,0.0,2.0,0.0,16,4,6,41.863734,-87.676313,POINT (-87.676312689993 41.863734390899),2017-06-14
4,420197,ef1b1d450f65c6d16245dffdd3304d93b8be7d7bbf47f3...,JB247942,NaN,2018-05-03 08:35:00,30,NO CONTROLS,NO CONTROLS,RAIN,DAYLIGHT,...,0.0,2.0,0.0,8,5,5,41.851794,-87.695223,POINT (-87.695223114296 41.851794251516),2018-05-03

*Transformaciones* básicas

In [5]:
Chicago_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27961 entries, 0 to 27960
Data columns (total 51 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     27961 non-null  int64
 1   CRASH_RECORD_ID                27961 non-null  object
 2   RD_NO                          27713 non-null  object
 3   CRASH_DATE_EST_I               2117 non-null   object
 4   CRASH_DATE                     27961 non-null  object
 5   POSTED_SPEED_LIMIT             27961 non-null  int64
 6   TRAFFIC_CONTROL_DEVICE         27961 non-null  object
 7   DEVICE_CONDITION               27961 non-null  object
 8   WEATHER_CONDITION              27961 non-null  object
 9   LIGHTING_CONDITION             27961 non-null  object
 10  FIRST_CRASH_TYPE               27961 non-null  object
 11  TRAFFICWAY_TYPE                27961 non-null  object
 12  LANE_CNT                       12418 non-null  float64
 13  ALIGNMENT                      27961 non-null  object
 14  ROADWAY_SURFACE_COND           27961 non-null  object
 15  ROAD_DEFECT                    27961 non-null  object
 16  REPORT_TYPE                    27294 non-null  object
 17  CRASH_TYPE                     27961 non-null  object
 18  INTERSECTION_RELATED_I         6155 non-null   object
 19  NOT_RIGHT_OF_WAY_I             1356 non-null   object
 20  HIT_AND_RUN_I                  7952 non-null   object
 21  DAMAGE                         27961 non-null  object
 22  DATE_POLICE_NOTIFIED           27961 non-null  object
 23  PRIM_CONTRIBUTORY_CAUSE        27961 non-null  object
 24  SEC_CONTRIBUTORY_CAUSE         27961 non-null  object
 25  STREET_NO                      27961 non-null  int64
 26  STREET_DIRECTION               27960 non-null  object
 27  STREET_NAME                    27961 non-null  object
 28  BEAT_OF_OCCURRENCE             27960 non-null  float64
 29  PHOTOS_TAKEN_I                 341 non-null    object
 30  STATEMENTS_TAKEN_I             564 non-null    object
 31  DOORING_I                      99 non-null     object
 32  WORK_ZONE_I                    158 non-null    object
 33  WORK_ZONE_TYPE                 125 non-null    object
 34  WORKERS_PRESENT_I              41 non-null     object
 35  NUM_UNITS                      27961 non-null  int64
 36  MOST_SEVERE_INJURY             27908 non-null  object
 37  INJURIES_TOTAL                 27910 non-null  float64
 38  INJURIES_FATAL                 27910 non-null  float64
 39  INJURIES_INCAPACITATING        27910 non-null  float64
 40  INJURIES_NON_INCAPACITATING    27910 non-null  float64
 41  INJURIES_REPORTED_NOT_EVIDENT  27910 non-null  float64
 42  INJURIES_NO_INDICATION         27910 non-null  float64
 43  INJURIES_UNKNOWN               27910 non-null  float64
 44  CRASH_HOUR                     27961 non-null  int64
 45  CRASH_DAY_OF_WEEK              27961 non-null  int64
 46  CRASH_MONTH                    27961 non-null  int64
 47  LATITUDE                       27800 non-null  float64
 48  LONGITUDE                      27800 non-null  float64
 49  LOCATION                       27800 non-null  object
 50  date_real                      27961 non-null  object
dtypes: float64(11), int64(7), object(33)
memory usage: 10.9+ MB

In [6]:
Chicago_df.describe()

,Unnamed: 0,POSTED_SPEED_LIMIT,LANE_CNT,STREET_NO,BEAT_OF_OCCURRENCE,NUM_UNITS,INJURIES_TOTAL,INJURIES_FATAL,INJURIES_INCAPACITATING,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE
count,27961.000000,27961.000000,12418.000000,27961.000000,27960.000000,27961.000000,27910.000000,27910.000000,27910.000000,27910.000000,27910.000000,27910.000000,27910.0,27961.00000,27961.000000,27961.000000,27800.000000,27800.000000
mean,223994.700976,28.250277,2.543727,3613.898037,1249.935622,2.032474,0.172375,0.000967,0.017628,0.097277,0.056503,2.021426,0.0,13.14066,4.125782,6.679124,41.854875,-87.669008
std,129369.418879,6.534930,2.868838,2834.728008,709.244576,0.442975,0.547166,0.033314,0.148726,0.403898,0.316171,1.164637,0.0,5.53616,1.983233,3.395461,0.443161,0.912675
min,5.000000,0.000000,0.000000,1.000000,111.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,1.000000,1.000000,0.000000,-87.933994
25%,112646.000000,30.000000,2.000000,1200.000000,715.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.0,9.00000,2.000000,4.000000,41.786318,-87.721236
50%,223910.000000,30.000000,2.000000,3132.000000,1214.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.0,14.00000,4.000000,7.000000,41.876850,-87.673489
75%,336419.000000,30.000000,4.000000,5500.000000,1824.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.0,17.00000,6.000000,10.000000,41.924793,-87.632824
max,447370.000000,99.000000,99.000000,13770.000000,2535.000000,11.000000,15.000000,2.000000,4.000000,11.000000,15.000000,38.000000,0.0,23.00000,7.000000,12.000000,42.022580,0.000000

Trabajando con fechas

In [7]:
Chicago_df['CRASH_DATE'] = Chicago_df['CRASH_DATE'].apply(lambda x: pd.to_datetime(x,
errors='coerce', utc=True))

In [8]:
Chicago_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27961 entries, 0 to 27960
Data columns (total 51 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     27961 non-null  int64
 1   CRASH_RECORD_ID                27961 non-null  object
 2   RD_NO                          27713 non-null  object
 3   CRASH_DATE_EST_I               2117 non-null   object
 4   CRASH_DATE                     27961 non-null  datetime64[ns, UTC]
 5   POSTED_SPEED_LIMIT             27961 non-null  int64
 6   TRAFFIC_CONTROL_DEVICE         27961 non-null  object
 7   DEVICE_CONDITION               27961 non-null  object
 8   WEATHER_CONDITION              27961 non-null  object
 9   LIGHTING_CONDITION             27961 non-null  object
 10  FIRST_CRASH_TYPE               27961 non-null  object
 11  TRAFFICWAY_TYPE                27961 non-null  object
 12  LANE_CNT                       12418 non-null  float64
 13  ALIGNMENT                      27961 non-null  object
 14  ROADWAY_SURFACE_COND           27961 non-null  object
 15  ROAD_DEFECT                    27961 non-null  object
 16  REPORT_TYPE                    27294 non-null  object
 17  CRASH_TYPE                     27961 non-null  object
 18  INTERSECTION_RELATED_I         6155 non-null   object
 19  NOT_RIGHT_OF_WAY_I             1356 non-null   object
 20  HIT_AND_RUN_I                  7952 non-null   object
 21  DAMAGE                         27961 non-null  object
 22  DATE_POLICE_NOTIFIED           27961 non-null  object
 23  PRIM_CONTRIBUTORY_CAUSE        27961 non-null  object
 24  SEC_CONTRIBUTORY_CAUSE         27961 non-null  object
 25  STREET_NO                      27961 non-null  int64
 26  STREET_DIRECTION               27960 non-null  object
 27  STREET_NAME                    27961 non-null  object
 28  BEAT_OF_OCCURRENCE             27960 non-null  float64
 29  PHOTOS_TAKEN_I                 341 non-null    object
 30  STATEMENTS_TAKEN_I             564 non-null    object
 31  DOORING_I                      99 non-null     object
 32  WORK_ZONE_I                    158 non-null    object
 33  WORK_ZONE_TYPE                 125 non-null    object
 34  WORKERS_PRESENT_I              41 non-null     object
 35  NUM_UNITS                      27961 non-null  int64
 36  MOST_SEVERE_INJURY             27908 non-null  object
 37  INJURIES_TOTAL                 27910 non-null  float64
 38  INJURIES_FATAL                 27910 non-null  float64
 39  INJURIES_INCAPACITATING        27910 non-null  float64
 40  INJURIES_NON_INCAPACITATING    27910 non-null  float64
 41  INJURIES_REPORTED_NOT_EVIDENT  27910 non-null  float64
 42  INJURIES_NO_INDICATION         27910 non-null  float64
 43  INJURIES_UNKNOWN               27910 non-null  float64
 44  CRASH_HOUR                     27961 non-null  int64
 45  CRASH_DAY_OF_WEEK              27961 non-null  int64
 46  CRASH_MONTH                    27961 non-null  int64
 47  LATITUDE                       27800 non-null  float64
 48  LONGITUDE                      27800 non-null  float64
 49  LOCATION                       27800 non-null  object
 50  date_real                      27961 non-null  object
dtypes: datetime64[ns, UTC](1), float64(11), int64(7), object(32)
memory usage: 10.9+ MB

In [9]:
Chicago_df['CRASH_DATE']

0       2017-02-14 10:00:00+00:00
1       2019-08-13 19:12:00+00:00
2       2019-05-22 08:30:00+00:00
3       2017-06-14 16:50:00+00:00
4       2018-05-03 08:35:00+00:00
                   ...
27956   2019-07-21 09:40:00+00:00
27957   2018-05-12 09:30:00+00:00
27958   2018-10-10 13:25:00+00:00
27959   2019-05-02 09:45:00+00:00
27960   2017-08-08 10:00:00+00:00
Name: CRASH_DATE, Length: 27961, dtype: datetime64[ns, UTC]

In [13]:
Chicago_df['NUM_UNITS']=Chicago_df['NUM_UNITS'].astype('int32')
Chicago_df['NUM_UNITS']

0        2
1        2
2        2
3        2
4        2
        ..
27956    1
27957    2
27958    2
27959    2
27960    2
Name: NUM_UNITS, Length: 27961, dtype: int32

In [11]:
import plotly.express as px
px.set_mapbox_access_token(token_map_plot)

ModuleNotFoundError: No module named 'plotly'

In [ ]:
df = px.data.carshare()
fig = px.scatter_mapbox(Chicago_df, lat="LATITUDE", lon="LONGITUDE",     color="CRASH_HOUR", size="NUM_UNITS",
                  color_continuous_scale=px.colors.cyclical.IceFire, size_max=15, zoom=10)
fig.show()

In [ ]:
Chicago_df['Lat_round']=round(Chicago_df['LATITUDE'],2)
Chicago_df['Long_round']=round(Chicago_df['LONGITUDE'],2)

In [ ]:
df = px.data.carshare()
fig = px.scatter_mapbox(Chicago_df, lat="Lat_round", lon="Long_round",     color="CRASH_HOUR", size="NUM_UNITS",
                  color_continuous_scale=px.colors.cyclical.IceFire, size_max=15, zoom=10)

In [ ]:
fig.show()